### ISSUE TITLE
I wonder if this tool supports link-level simulation under turbulence? 

### ISSUE THREAD

**Issue by goodgoodlearn** [ojdf/fast#3]
I mean, simulate sending bit stream and receiving bit stream and calculate bit error rate.

**Comment by ojdf** [comment]
Hi @goodgoodlearn, this is currently supported (experimentally) in the ```fast.comms.Modulator``` class. The usage would be something like this 

```
import fast

modulation_scheme = "QAM" # see fast.comms.define_constellation for possible modulation schemes 
EsN0 = 10 # signal to noise per symbol

sim = fast.Fast("params_file.py")
sim.run()
# simulation will run and produce output 

mod = fast.comms.Modulator(sim.result.power, modulation_scheme,  EsN0)
mod.run()

print(mod.sep)
```

This would print out the symbol error probability for random bits given the channel characterised with the Fast simulation. I am also working on providing custom binary data (see the ```data``` kwarg to the ```Modulator``` class), if that is something you are interested in we can have a more detailed look. 

Thanks 
Ollie
